version: '3'

services:
  angular:
    networks:
      gallerynet:
    image: cianmc/angular-gallery-app:latest
    ports:
      - '4200:4200'

  express:
    networks: 
      gallerynet:
    image: cianmc/node-gallery-app:latest
    ports:
      - '3000:3000'
    environment:    
      HOST: 192.168.0.1
      DOCKER: tcp://192.168.0.1:2375
      DIR: "${DIR:?err}"
    volumes:
      - ./config/:/usr/src/app/mounts/config/
      - ./dashboard/:/usr/src/app/dashboard/

networks: 
  gallerynet:
    external: true
